gen:
	cd ..; make clean vow_gen_swig

sidh128:
	cd ..; make clean vow_sidh_swig128

sidh434:
	cd ..; make clean vow_sidh_swig434

sike128:
	cd ..; make clean vow_sike_swig128

sike434:
	cd ..; make clean vow_sike_swig434

.PHONY: gen sidh128 sidh434 sike128 sike434